### ISSUE TITLE
A Tour of C++ recommends against using naked pointers.

### ISSUE THREAD

**Issue by EliteTK** [dean1012/memes-with-friends#21]
I'm just putting this here as a reminder for myself to go through the project and try to remove as much use of naked pointers as possible, as it's opening up the project to memory leaks.

Specifically unique_ptr or shared_ptr should be used instead of naked pointers to things like classes.

**Comment by EliteTK** [comment]
Very soon all naked pointers will likely be gone.

**Comment by dean1012** [comment]
I am closing this issue. We have eliminated all the naked pointers I'm aware of and will continue to make sure naked pointers are not in use.
