### ISSUE TITLE
VCRUNTIME1400D.dll, ucrtbased.dll missing from system

### ISSUE THREAD

**Issue by TheTerrorByte** [dean1012/memes-with-friends#4]
After the game is run, the game does not start due to missing files.

![mwf1](https://cloud.githubusercontent.com/assets/8520072/26531357/4d3b4834-439c-11e7-8e56-5d2571cfdf88.png)
![mwf2](https://cloud.githubusercontent.com/assets/8520072/26531358/4d3d03ea-439c-11e7-8b8d-80a62edec6fb.png)

**Comment by dean1012** [comment]
Please redownload the zip file and extract again. I accidentally uploaded a debug version of the app instead of release version.

Please let me know if it works (or not)

**Comment by TheTerrorByte** [comment]
ucrt is fixed, VCruntime still missing

**Comment by dean1012** [comment]
Try downloading and installing this and let me know if it's successful or not. If not, please include another screenshot.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by TheTerrorByte** [comment]
Working. Note I had to install both of them for it to work.
![mwf3](https://cloud.githubusercontent.com/assets/8520072/26532486/bb800d56-43b6-11e7-8d05-dac08d9c70fa.png)

**Comment by dean1012** [comment]
Closing this issue. It seems the runtime environment fixed the issue. Please create a new issue if problem persists.
