### ISSUE TITLE
Corner text hard to read

### ISSUE THREAD

**Issue by TheTerrorByte** [dean1012/memes-with-friends#9]
![mwf7](https://cloud.githubusercontent.com/assets/8520072/26614596/59c050a0-4576-11e7-95a4-287d7bd59b2a.png)

res: 1366x768

**Comment by dean1012** [comment]
Thanks for reporting. I can try to increase the font size used slightly (12 -> 14 perhaps, or even 12 -> 16) on resolutions smaller than 1920x1080. It might cause slight positional issues but we can try to work around that.

If that doesn't help any, then it's definitely a factor of the scaling and I'm not sure what else to do about it at the moment.

**Comment by dean1012** [comment]
Please check this build to see if it fixes this issue and #11 
Let me know the results (with screenshot if possible) and I'll close this if it's fixed.

**Comment by dean1012** [comment]
Closing due to non-response. If the issue persists, please reopen or create a new issue referencing this one.
